version: '3.8'

networks:
  shared_db_network:
    external: true

services:
  invenmaster-dev:
    image: shivaak/invenmaster:0.0.1-SNAPSHOT-dev
    container_name: invenmaster-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 6001
      DB_URL: ${DEV_DB_URL}
      DB_USERNAME: ${DEV_DB_USERNAME}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "${SERVER_PORT:-6001}:${SERVER_PORT:-6001}"
    networks:
      - shared_db_network
    restart: unless-stopped
