version: '3.8'

networks:
  shared_db_network:
    external: true

services:
  invenmaster-staging:
    image: invenmaster:latest
    container_name: invenmaster-staging
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SERVER_PORT: 6001
      DB_URL: ${STAGING_DB_URL}
      DB_USERNAME: ${STAGING_DB_USERNAME}
      DB_PASSWORD: ${STAGING_DB_PASSWORD}
    ports:
      - "6001:6001"
    networks:
      - shared_db_network
