version: '3.8'

networks:
  shared_db_network:
    external: true

services:
  invenmaster-dev:
    image: invenmaster:latest
    container_name: invenmaster-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 6001
      DB_URL: ${DEV_DB_URL}
      DB_USERNAME: ${DEV_DB_USERNAME}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "6001:6001"
    networks:
      - shared_db_network
