version: '3.8'

networks:
  shared_db_network:
    external: true

services:
  invenmaster-local:
    image: invenmaster:latest
    container_name: invenmaster-local
    environment:
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - shared_db_network
