spring:
  application:
    name: invenmaster-local
  datasource:
    url: jdbc:postgresql://localhost:5432/invenmaster_local
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8080}