spring:
  application:
    name: invenmaster-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/invenmaster
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
